apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AlexChavdarov/podinfo-repo.git
  secretRef:
    name: flux-git-auth  # Тук се добавя референцията към създадения секрет
