apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  path: ./podinfo
  sourceRef:
    kind: GitRepository
    name: flux-k8s-deployment
  prune: true
  resources:
    - ./podinfo/deployment.yaml
    - ./podinfo/podinfo-deployment.yaml
    - ./podinfo/flux-kustomization.yaml
    - ./podinfo/service.yaml
    - ./podinfo/podinfo.yaml
