apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 2  # Брой реплики на подовете
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: quay.io/stefanprodan/podinfo:latest  # Връзка към образа на podinfo
          ports:
            - containerPort: 9898  # Порт, на който ще слуша podinfo
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # Сетиране на името на пода като променлива
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace  # Сетиране на името на неймспейса като променлива
